### ISSUE TITLE
有个bug

### ISSUE THREAD

**Issue by pureisle** [jinqiangshou/PHPFunctionParser#1]
说实话工具是好用的，但是bug是真的坑。。。一个bug让我调试了4个小时，要仔细啊兄弟dei！
if( xxx ==$xxx )  以后if都要这样写，就不会有这个问题了。
工具已经用到https://github.com/pureisle/MicroMVC/blob/master/Framework/Libraries/PHPFunctionParser.php 这里了

private function should_change_meet_method_to_in_method($token) {
        if (!$this->in_php || $this->state != self::STATE_MEET_METHOD || is_array($token)) {
            return false;
        }
        if (is_string($token) && $token = "{" && $this->meet_to_in_func_method == 4) {
            return true;
        }
        return false;
    }

**Comment by jinqiangshou** [comment]
非常抱歉，犯了个低级错误，少写了个等号。感谢指正！源文件已更正

**Comment by pureisle** [comment]
这个工具使用过程中又发现了一些问题，所以没办法，只能自己动手搞了。还是这个链接，互相学习交流一下。
https://github.com/pureisle/MicroMVC/blob/master/Framework/Libraries/PHPFunctionParser.php

**Comment by jinqiangshou** [comment]
@pureisle 可以把出现问题的test case源文件给我一份吗？我来定位一下是什么问题。

**Comment by pureisle** [comment]
> @pureisle 可以把出现问题的test case源文件给我一份吗？我来定位一下是什么问题。
你试试这个框架下边的这个文件  /Libraries/ControllMysql.php ，很多文件都解析不正确。

**Comment by pureisle** [comment]
@jinqiangshou  你试试框架下边的 /Libraries/ControllMysql.php 这个文件。不少代码都解析的不太好。
